version: "3.9"

services:
  tg-bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs  # Optional: Map logs directory for persistence
    network_mode: "host"
    restart: unless-stopped